services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: clickboard-api
    working_dir: /app/apps/api
    environment:
      - NODE_ENV=development
      - PORT=3001
      - HOST=0.0.0.0
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
    # instala dependências no volume e só então inicia o Nest com watch
    command: sh -lc "pnpm install && pnpm start:dev"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: clickboard-web
    working_dir: /app/apps/web
    environment:
      - VITE_API_URL=http://localhost:3001
      - CHOKIDAR_USEPOLLING=1
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/web/node_modules
    command: ["pnpm","dev","--","--host","0.0.0.0"]
